version: 2.1

orbs:
  cypress: cypress-io/cypress@3

jobs:
  build:
    docker:
      - image: cypress/base:12.18.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build app
          command: npm run build
      - run:
          name: Start server
          command: npm run start
      - run:
          name: Wait for server to be ready
          command: wait-on http://localhost:3000

  test:
    docker:
      - image: cypress/base:12.18.3
    steps:
      - checkout
      - run:
          name: Run Cypress tests
          command: npm run cypress:run

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
